# Generated by Django 3.1.7 on 2021-03-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jets',
            old_name='user',
            new_name='added_by',
        ),
    ]
